name: Publish patch

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: |
          git config user.name "Serhii Mykhailenko"
          git config user.email "newsklog@gmail.com"
          npm version patch
          git push origin master
          git push origin --tags
      - run: npm run build
      - run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
